---
title: "1_journal_transparency"
author: "Michael Vincenzo Petrone"
output: html_document
date: "2025-07-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Imports
``` {r}
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
data <- read.csv("./data.csv")
library(dplyr)
```

Transparency Score Key

-   $\mathbf{N/A}$ = No data no code
-   $\mathbf{1}$ = Poorly shared data or code
-   $\mathbf{2}$ = Some shared data or code but not accessible
-   $\mathbf{3}$ = Some shared data or code and partially accessible
-   $\mathbf{4}$ = Some shared data or code and fully accessible
-   $\mathbf{5}$ = Fully shared data and code and fully accessible

```{r,  setup=FALSE}
average_transparency <- data %>%
  group_by(Journal) %>%
  summarise(AvgTransparency = round(mean(Transparency.score..1.5.), 2))
print(average_transparency)
```

Bar Chart Depiction

```{r, setup=FALSE}
sorted_data <- average_transparency[order(average_transparency$AvgTransparency), ]

barplot(
  sorted_data$AvgTransparency,
  names.arg = sorted_data$Journal,
  main = "Average Transparency Score by Journal",
  xlab = "Journal",
  ylab = "Average Transparency Score",
  col = "steelblue",
  las = 2,  # Rotate axis labels for readability
  ylim = c(0, 5)  # Set the y-axis to range from 0 to 5
)

```

